### ISSUE TITLE
Additional Opt-Outs

### ISSUE THREAD

**Issue by avuserow** [jmhobbs/beef-taco#10]
Hi, I found a few more places to potentially opt out of from http://www.aboutads.info/choices/

Listed for me are:
- Clearspring Technologies, Inc
- Invite Media
- Rocket Fuel, Inc

**Comment by jmhobbs** [comment]
Thanks!  That link is a great resource, I'm adding them in now.

**Comment by jmhobbs** [comment]
Just submitted 1.3.5 to AMO.  Pending review this item is done.  Thanks!
